### PR TITLE
rename h-at to h-auto so it matches w-auto

### PR DESCRIPTION
**Pull request by martinklepsch**
via https://github.com/tachyons-css/tachyons/pull/186

### CODE REVIEW

**Comment by martinklepsch** [comment]
Just figured this needs to be updated in other places besides `src/` as well. Will work it out...

**Comment by martinklepsch** [comment]
The alignment in the source file is either a bit irregular or I just don't get it. Let me know if you want this updated in any way. Also happy to squash commits if you prefer that. I think it's reasonable to keep updates to generated files in separate commits. :)

Also just wanted to say thanks for all your work & writing on this, it brings back the fun in designing for the web 👍

**Comment by mrmrs** [comment]
@martinklepsch Ah thanks a bunch for the kind words. Makes my day to hear I've made designing for the web fun again! 

Thank you even more for your contribution here. Much appreciated. I also updated the i class to spell inherit as I think that is more clear and consistent. Bumped the version to version 5 as technically these are breaking changes.

Will update the main tachyons repo soon.

**Comment by martinklepsch** [comment]
👍  💯

**Pull request merged**
